### ISSUE TITLE
Aliases should be used if present

### ISSUE THREAD

**Issue by pettax** [foursquare/datasource-plugin-clouderamanager#1]
Currently, the time series shows up as metricName (entityName) in my panels. If the user has given an alias in the query I think the alias should have precedence. The current output is very crowded, especially in the new Table panel.

Eg.
select health_good_rate as "Hive" where entityName="HIVE-1"
now renders as
health_good_rate (HIVE-1)

but if the alias was respected it would render as just
Hive

I have modified here locally to the below and it took my table panels to the next level.

```
// Convert the metadata returned from Cloudera Manager into the timeseries name for Grafana.
ClouderaManagerDatasource.prototype._makeTimeseriesName = function(metadata) {
  if (metadata.alias) {
    return metadata.alias;
  } else if  (metadata.metricName && metadata.entityName) {
    return metadata.metricName + ' (' + metadata.entityName  + ')';
  } else if (metadata.metricName) {
    return metadata.metricName;
  } else if (metadata.entityName) {
    return metadata.entityName;
  } else {
    return 'UNKNOWN NAME';
  }
};
```

**Comment by tdyas** [comment]
Merged https://github.com/foursquare/datasource-plugin-clouderamanager/pull/2
