### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by golak** [foursquare/datasource-plugin-clouderamanager#4]
I try to build docker image based on grafana-xxl with
grafana-cli plugins install foursquare-clouderamanager-datasource

And get error:
Error: Could not access https://grafana.net/api/plugins/repo/foursquare-clouderamanager-datasource statuscode 404

**Comment by tdyas** [comment]
You're seeing the repository in an intermediate state while I get `grafana-cli` installs setup. Wait a day or so. I need to make a pull request to the Grafana plugin registry at https://github.com/grafana/grafana-plugin-repository for `grafana-cli` to know what to do.

**Comment by tdyas** [comment]
In the meantime, you can just clone the repository into your plugins directory.

**Comment by golak** [comment]
Thanks, git clone is working. But after add datasource get:

```
Data source is working. API version is '<!-- __CLOUDERA__PRE__LOGIN__FORM__ --> <!DOCTYPE html> <head> <meta charset="utf-8"> </head> <html> <body></body> </html> <script type="text/javascript"> var returnUrl = window.location.pathname + window.location.search + window.location.hash; var loginPageUrl = "/cmf/login"; if (returnUrl !== "/cmf" && returnUrl !== "/cmf/" && returnUrl !== "/cmf/home" && returnUrl !== "/cmf/home/") { loginPageUrl = loginPageUrl + "?returnUrl=" + encodeURIComponent(returnUrl); } window.location = loginPageUrl; </script> '.
```

And after add metric

```
Error 403 Invalid request. Please check Cloudera Manager Server logs for more details.

HTTP ERROR 403
Problem accessing /cmf/preLogin. Reason:
    Invalid request. Please check Cloudera Manager Server logs for more details.Powered by Jetty://   
```

Version: Cloudera Express 5.8.1

**Comment by tdyas** [comment]
What URL did you specify? The API version should have showed as a number, not the login page.

**Comment by golak** [comment]
http://cloudera.hdp:7180/cmf/

cloudera.hdp - my local dns record

**Comment by golak** [comment]
![image](https://cloud.githubusercontent.com/assets/1150258/19481842/f1a228e6-9557-11e6-8b1d-d9b34dce6b95.png)

**Comment by tdyas** [comment]
Remove the /cmf/ bit. The datasource will add the correct path used by the CM API.

**Comment by golak** [comment]
It's working! Thank you!

**Comment by anshurajkaushik** [comment]
i am able to add data source with https:/cm_host/cmf , howwver with cmf bit , i am not able to do tsquery , if i remove cmf bit , data source is not getting addedd with https
