### ISSUE TITLE
Error while creating Alerts in Grafana

### ISSUE THREAD

**Issue by veeragarapati** [foursquare/datasource-plugin-clouderamanager#6]
Hi,
I'm facing the below issue while creating and testing an alert for CM datasource. 

> result
> firing true
> state alerting
> conditionEvals = true
> timeMs 0.821ms
> error tsdb.HandleRequest() error Could not find executor for data source type: foursquare-clouderamanager-datasource

**Comment by tdyas** [comment]
The core Grafana server would need to be modified to support alerting for this datasource. I do not have the time to do that.
